### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by FloTheSysadmin** [nikaro/wirelogd#100]
Hi @nikaro. Would it be okay for you If I created an AUR Package for this project? I am new to the AUR and trying to learn. 
Thank you for your Feedback.

**Comment by nikaro** [comment]
Hi @RichardRMatthews yep i'm definitely okay with it! Feel free to post your `PKGBUILD` file here for review. I already did a few AUR package and may help if needed.

BTW, GoReleaser could be used to publish a `wirelogd-bin` AUR package, i do it for another project i maintain and it is pretty straightforward to do: https://github.com/nikaro/goresume/blob/main/.goreleaser.yml#L14. `wirelogd` would probably need some customizations (systemd service, etc.) though.

**Comment by RichardRMatthews** [comment]
@nikaro thank you for your Feedback. I will try my best. Do you know how I could best create the wirelog users im PKGBUILD? Or is there another solution?

Thank you for the input.

**Comment by nikaro** [comment]
@RichardRMatthews you can take a look at how the [graylog](https://aur.archlinux.org/packages/graylog) AUR package does it in the [`graylog.install`](https://aur.archlinux.org/cgit/aur.git/tree/graylog.install?h=graylog&id=da12b40e3e1db08af63e1329f834dde4d3b00454) file along the `PKGBUILD` one. The [libreoffice-online](https://gitlab.archlinux.org/archlinux/packaging/packages/libreoffice-online/-/blob/main/libreoffice-online.install?ref_type=heads) package do something like this also.

But may be an even better way to do it is to follow how [traefik](https://gitlab.archlinux.org/archlinux/packaging/packages/traefik/-/blob/main/PKGBUILD#L51) do it by using a [systemd-sysusers file](https://man.archlinux.org/man/sysusers.d.5.en) to declaratively create the user. That's probably how i would do it.

**Comment by FloTheSysadmin** [comment]
Hi, sorry I was AFK for a few days. I created an AUR repo. Please review it and tell me what you think. Thank you.

https://aur.archlinux.org/packages/wirelogd

**Comment by nikaro** [comment]
Looks good to me! Thanks!
