### ISSUE TITLE
build on Debian fails when PREFIX is changed; Config File "config" Not Found in "[/etc/wirelogd]"

### ISSUE THREAD

**Issue by jtmoon79** [nikaro/wirelogd#12]
I attempted to build `wirelogd` on a Raspberry Pi.  I changed the make install `PREFIX` from `/usr` to `/opt/wirelogd`. There were several errors.

```text
$ git clone https://github.com/nikaro/wirelogd.git
$ cd wirelogd
$ make
Building...
env CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -mod vendor -o build/wirelogd-linux-arm .
build/wirelogd-linux-arm man > man/wirelogd.1
{"level":"warn","error":"Config File \"config\" Not Found in \"[/etc/wirelogd]\"","time":"2022-08-02T13:10:03-07:00"}
build/wirelogd-linux-arm completion bash > completions/wirelogd.bash
{"level":"warn","error":"Config File \"config\" Not Found in \"[/etc/wirelogd]\"","time":"2022-08-02T13:10:03-07:00"}
build/wirelogd-linux-arm completion fish > completions/wirelogd.fish
{"level":"warn","error":"Config File \"config\" Not Found in \"[/etc/wirelogd]\"","time":"2022-08-02T13:10:03-07:00"}
build/wirelogd-linux-arm completion zsh > completions/wirelogd.zsh
{"level":"warn","error":"Config File \"config\" Not Found in \"[/etc/wirelogd]\"","time":"2022-08-02T13:10:03-07:00"}
```
Despite the warnings, `make` process return code is `0`.

Then install fails
```text
$ make PREFIX=/opt/wirelogd install
Installing...
install -Dm755 build/wirelogd-linux-arm /opt/wirelogd/bin/wirelogd
install -Dm644 man/wirelogd.1 /opt/wirelogd/share/man/man1/
install: target '/opt/wirelogd/share/man/man1/' is not a directory: No such file or directory
make: *** [Makefile:42: install] Error 1
```
The `make` process return code is `2`.

I worked around the error by running
```text
$ mkdir -vp /opt/wirelogd/share/man/man1/
```
then repeating the `make ... install` command.

The file `wirelogd-nopasswd` was not at `/usr/share/wirelogd/wirelogd-nopasswd`. I did find it in the git directory at `./contrib/wirelogd-nopasswd`.

Lastly, I had to adjust file `/etc/systemd/system/wirelogd.service` line from `ExecStart=/usr/bin/wirelogd` to `ExecStart=/opt/wirelogd/bin/wirelogd`.

The service successfully started after running
```text
$ systemctl daemon-reload
$ systemctl start wirelogd
```

---

Using go 1.19, GNU make 4.2.1.

<br/>

Despite the workarounds, the service is running. Thanks for creating this valuable logging service! 😊

**Comment by nikaro** [comment]
Hello @jtmoon79,

Thank you for your report.

> I attempted to build wirelogd on a Raspberry Pi. I changed the make install PREFIX from /usr to /opt/wirelogd. There were several errors.

It was just some noise, `man` and `completion` subcommands tried to load the inexistant (at this step) config file. Anyway, it should now be fixed.

> The make process return code is 2.

My bad, bad usage of the `install` tool. It is now fixed.

> The file wirelogd-nopasswd was not at /usr/share/wirelogd/wirelogd-nopasswd. I did find it in the git directory at ./contrib/wirelogd-nopasswd.

This file should not be needed anymore, it was used by the Python version of this app which was using `sudo wg...` commands. Now, with the capabilities (`CAP_NET_ADMIN`) set by the systemd service it is sufficient.

> Lastly, I had to adjust file /etc/systemd/system/wirelogd.service line from ExecStart=/usr/bin/wirelogd to ExecStart=/opt/wirelogd/bin/wirelogd.

It is fixed, i've added a sed in the `Makefile`.

> Despite the workarounds, the service is running. Thanks for creating this valuable logging service! 😊

I'm glad it have been helpful to at least someone else than me :-)
