### ISSUE TITLE
Wirelogd fails to start on debian without debug set

### ISSUE THREAD

**Issue by xschlef** [nikaro/wirelogd#22]
Hi,

wirelogd will not come up via systemd if debug is not set via commandline (config does not work).

First log line reads:
`wirelogd[11909]: {"level":"warn","error":"While parsing config: toml: expected 'nan'","time":"2022-10-18T15:22:44+02:00"}`

My workaround is to override the systemd unit file with -d...

I am using the v1.0.1 debian amd64 package release.

**Comment by nikaro** [comment]
The log line it just a warning, it should not prevent the service to start.

Can you share the content of your `/etc/wirelogd/config.toml` config file?

May be try to replace `debug = no` by `debug = false` to see if it fixes the warning.
